### PR TITLE
Move `rand` to dev-dependencies, implement std::fmt::Debug, and more.

### PR DESCRIPTION
**Pull request by utkarshkukreti**
Each commit explains the changes and the motivation.

I'd really appreciate a new release on crates.io after you merge this (I've included a version bump commit).

Also, thank you for maintaining this after it was removed from `std::sync`!

### CODE REVIEW

**Comment by kinghajj** [comment]
I'll try to remember to publish a new version once I'm back home. No problem, hopefully I can be a more-active maintainer of this crate going forward!

**Comment by utkarshkukreti** [comment]
Thanks!

Just reminding in case you forgot to publish the new version. :)

**Comment by kinghajj** [comment]
Finally got around to it last night, sorry for all the delay!

**Comment by utkarshkukreti** [comment]
No worries, thanks!

**Pull request merged**
